// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://rqzyjpitzsrqtwpdbuph.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxenlqcGl0enNycXR3cGRidXBoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI3MDk0MTAsImV4cCI6MjA0ODI4NTQxMH0.jzPQoIfvyfOBigLk5EVfkqp-Erx__B7nrzKasn14_Gc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);